services:
  ntra_web:
    container_name: ntra_web
    image: nginx:alpine  # Use the Nginx image
    ports:
      - "9090:80"  # Map port 8080 on the host to port 80 inside the container
    volumes:
      - ./:/var/www  # Mount the Laravel application directory
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
    depends_on:
      - ntra_app  # Ensure PHP-FPM is started before Nginx
    networks:
      - ntra-network  # Connect to the custom network

  ntra_app:
    container_name: ntra_app
    build: .  # Build from the Dockerfile
    depends_on:
      - ntra_db
    volumes:
      - ./:/var/www  # Mount the Laravel application directory
    networks:
      - ntra-network  # Connect to the custom network

  ntra_db:
    container_name: ntra_db
    image: mysql:8  # Use MySQL image
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}  # Create a database named 'laravel'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Set the root password for MySQL
    volumes:
      - ntra_db_data:/var/lib/mysql  # Persist MySQL data
    networks:
      - ntra-network  # Connect to the custom network

  ntra_node:
    container_name: ntra_node
    image: node:20
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - ntra-network
    command: bash -c "npm install && npm run build && npm run dev"

# Define the custom network
networks:
  ntra-network:  # Create a custom network named 'ntra-network'
    driver: bridge

# Define the volume for MySQL data persistence
volumes:
  ntra_db_data: