services:
  ntra-web:
    container_name: ntra-web
    image: nginx:alpine  # Use the Nginx image
    ports:
      - "9090:80"  # Map port 8080 on the host to port 80 inside the container
    volumes:
      - ./:/var/www  # Mount the Laravel application directory
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
    depends_on:
      - ntra-app  # Ensure PHP-FPM is started before Nginx
    networks:
      - ntra-network  # Connect to the custom network

  ntra-app:
    container_name: ntra-app
    build:
      context: .
      dockerfile: Dockerfile # Build from the Dockerfile
    restart: unless-stopped
    depends_on:
      - ntra-postgres
    volumes:
      - ./:/var/www  # Mount the Laravel application directory
    networks:
      - ntra-network  # Connect to the custom network

  ntra-postgres:
    image: postgres
    container_name: ntra-postgres
    restart: always
    expose:
      - 5432
    ports:
      - "2346:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ntra_postgres_data:/var/lib/postgresql/data
    networks:
      - ntra-network

  ntra-pgadmin:
    image: dpage/pgadmin4
    container_name: ntra-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - ntra-network

  ntra-node:
    image: node:20
    container_name: ntra-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - ntra-network
    command: bash -c "npm install && npm run build && npm run dev"

networks:
  ntra-network:
    driver: bridge

volumes:
  ntra_postgres_data: